version: "3"

services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    depends_on:
      - backend
    networks:
      - nw

  backend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: ["npm", "run", "dev"]
    depends_on:
      - mongodb
    networks:
      - nw

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - nw

networks:
  nw:
    driver: bridge
