version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_USER: me
      DB_HOST: postgres
      DB_NAME: counter_db
      DB_PASSWORD: password
      DB_PORT: 5432
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - app-networks

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-networks

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: password
      POSTGRES_DB: counter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge

volumes:
  postgres_data:
