version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

networks:
  app-networks:
    driver: bridge
    