version: "3"

services:
  webserver:
    image: nginx
    ports:
      - "8081:80"
    restart: always
    networks:
      laliga:
        ipv4_address: 192.168.92.21

  webserver2:
    image: nginx
    ports:
      - "8082:80"
    restart: always

networks:
  laliga:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"